### ISSUE TITLE
Add ISOAnchor to a thesaurus

### ISSUE THREAD

**Issue by juliettefabre** [eblondel/geometa#102]
Inspire recommends to provide keywords and thesaurus with an URI, eg the "GEMET - INSPIRE themes, version 1.0"  thesaurus should be described with the URI "http://www.eionet.europa.eu/gemet/inspire_themes".
In geometa, it's possible for keywords, but i did not found a way to provide an URI for a thesaurus?

**Comment by eblondel** [comment]
Hi @juliettefabre since it was quite straighforward, i've just pushed some change that allows that (until now it was forced to be a string). You can apply the following to define your thesaurus:

```{r}
th <- ISOCitation$new()
th_ref <- ISOAnchor$new(name = "GEMET - INSPIRE themes, version 1.0", href="http://www.eionet.europa.eu/gemet/inspire_themes")
th$setTitle(th_ref)
inspire_date <- ISODate$new()
inspire_date$setDate("2008-06-01")
inspire_date$setDateType("publication")
th$addDate(inspire_date)
```

Let me know if it works for you

**Comment by juliettefabre** [comment]
Great, it works! Thanks a lot!

**Comment by eblondel** [comment]
Great, let me know how it goes with INSPIRE meta validation!

**Comment by juliettefabre** [comment]
No more warning!
