### ISSUE TITLE
truncation of XML file with $save method

### ISSUE THREAD

**Issue by eblondel** [eblondel/geometa#129]
Users reported that certain ISO 19139 XML files resulting from the ``$save`` got truncated at the end. 

Note for metadata publication: This issue might affect publication with [geonapi](https://github.com/eblondel/geonapi) ``insertMetadata`` / ``updateMetadata`` or [ows4R](https://github.com/eblondel/ows4R) ``insertRecord`` / ``updateRecord`` if and only if users rely on the ``file`` argument. Instead, it's recommended that users use the ``geometa`` argument in these functions. Indeed, publication with  [geonapi](https://github.com/eblondel/geonapi) and [ows4R](https://github.com/eblondel/ows4R)  does not require to write the XML as file. With the argument ``geometa``, both packages will call the method ``$encode``.

**Comment by eblondel** [comment]
@mrouan Can you re-install geometa from Github and check your Rscript if ``save`` works properly now (with no truncated XML)? Thanks in advance

**Comment by mrouan** [comment]
Hi @eblondel,
the XML is no more truncated, but its ending with a NUL character, just after the </gmd:MD_Metadata>.
When I try to import it in geonetwork it raise an error : 
`JDOMParseException
Error on line 493: Content is not allowed in trailing section.`
When I delete this character, everything is ok

**Comment by eblondel** [comment]
Ok, this should be fixed with https://github.com/eblondel/geometa/commit/158ee2c8e6d786c63be52d6bd6754970dd27066d Can you try again?
