### ISSUE TITLE
Error during communication with INSPIRE validation web-service

### ISSUE THREAD

**Issue by juliettefabre** [eblondel/geometa#159]
Hi Emmanuel, 

I get an error when trying to use the Inspire validator:
```
> md$encode(inspire = TRUE)`
Error in inspireValidator$getValidationReport(obj = self) : 
  Error during communication with INSPIRE validation web-service!
```
It used to work .. I use geometa_0.6-0. 

Thanks!
Juliette

**Comment by eblondel** [comment]
If you the latest from github I had to switch to the new INSPIRE reference
validator. The service previously used has been dismissed by Inspire team.
This said even with the new service you may experiments errors in case of
service unavailability. For the new validator, geometa first does a ping on
the servicr to see if it is up and running. If you get an error it means
that the service is temporarily unavailable.

Check at https://github.com/inspire-eu-validation/community

Le ven. 30 août 2019 16:33, juliettefabre <notifications@github.com> a
écrit :

**Comment by eblondel** [comment]
It seems it is temporarily available now, see https://github.com/inspire-eu-validation/community/issues/104

**Comment by eblondel** [comment]
@juliettefabre With the latest geometa@master, in case of service unavailability you will get the following warning ``INSPIRE Reference validator web-service is currently down. Skipping INSPIRE validation`` (and the INSPIRE validation will be skipped to avoid any blocking R error)

**Comment by juliettefabre** [comment]
Thanks a lot!

**Comment by eblondel** [comment]
@juliettefabre let me know if it works for you, if yes then you can close this ticket. Cheers

**Comment by juliettefabre** [comment]
@eblondel I downloaded the latest geometa@master, 1 hour ago I still got the "Error during communication with INSPIRE validation web-service" error, but now the Inspire validation is running ..

**Comment by eblondel** [comment]
This log message is an old message not anymore used in R code. 
When reinstalling, if you are in Rstudio, make sure to Restart the R session before, otherwise Rstudio may stick with the previous package in cache. This may explain why you got it.

**Comment by juliettefabre** [comment]
Yes I can't figure why I don't install the latest geometa, I restarted Rstudio before reinstalling, and even removed the geometa package .. Anyway, I close this ticket ;)
