### ISSUE TITLE
Mapping to EML produces weird thesaurus

### ISSUE THREAD

**Issue by juliettefabre** [eblondel/geometa#160]
Hi Emmanuel,

I want to test the mapping tools to EML and NetCDF, but I can't reproduce the examples provided in the [wiki](https://github.com/eblondel/geometa/wiki#mapping).

First I can't find the `getMappingFormats` function.

Then when I try the EML mapping I get an error :
```
> my_emld <- as(md, "emld")
Error in from_element_obj != item$attrs$element$value : 
  comparaison (2) possible seulement pour les types liste et atomique
```

Finally the NetCDF mapping seems to provide a really light ISOMetadata object compared to the nc object ..
```
> nc <- ncdf4::nc_open("http://gsics.eumetsat.int/thredds/dodsC/DemoLevel1B25Km/W_XX-EUMETSAT-Darmstadt,SURFACE+SATELLITE,METOPA+ASCAT_C_EUMP_20131231231800_37368_eps_o_125_l1.nc")
> test_ogc_cf <- as(nc, "ISOMetadata")
> test_ogc_cf
<ISOMetadata>
....|-- characterSet <ISOCharacterSet>: utf8 {8-bit variable size UCS Transfer Format, based on ISO/IEC 10646}
........|-- value: utf8
....|-- hierarchyLevel <ISOHierarchyLevel>: dataset {information applies to the dataset}
........|-- value: dataset
....|-- dateStamp: 2019-08-30 15:20:30
```

I work with geometa_0.6-0.
Any idea? Did I miss something?

Thanks,
Juliette

**Comment by eblondel** [comment]
0.6 is pending master, can you first confirm you work with the latest
master code?

Le ven. 30 août 2019 16:39, juliettefabre <notifications@github.com> a
écrit :

**Comment by eblondel** [comment]
For Netcdf-Cf, I've fixed a typo in some of the recent changes https://github.com/eblondel/geometa/commit/2c1740514d09f8f03bfd71b0f93f032da2f52d81 You can reinstall and test.

For EML, I don't know which kind of md objet you try to convert so it's hard to reproduce.

Generally speaking, the metadata converter is still experimental stage. It may need consolidation based on user tests. In addition, the metadata elements covered so far are minimum business metadata, which means conversion of a rich metadata object may imply a loss of metadata information. 

The metadata mapping rules defined so far are listed at https://github.com/eblondel/geometa/blob/master/inst/extdata/mappings/geometa_mapping.csv I also maintaining an online version at https://docs.google.com/spreadsheets/d/1N-Xpp8-YjVzQ4CORfdas_9CaRV4hdrRKPbO4xXNs8-Q/edit?usp=sharing 

On the limitations of mapping NetCDF-CF to geometa, I used this source of information https://geo-ide.noaa.gov/wiki/index.php?title=NetCDF_Attribute_Convention_for_Dataset_Discovery but please note that for now I don't map it to 19115-2 but 19115-1, due to the fact that ISO 19115-2 was supported after the metadata converter was developed. I foresee an improvement to make sure to use ISO 19115-2 in case source object is a ncdf4 object.

**Comment by eblondel** [comment]
https://github.com/eblondel/geometa/issues/161

**Comment by juliettefabre** [comment]
@eblondel yes I confirm that I work with the latest geometa@master.

Thanks for your explanations.

For NetCDF now I get a more complex ISOMetadata object, perfect.

For EML, I tested with a "complete" ISOMetadata object (similar to the one [described in the geometa wiki](https://github.com/eblondel/geometa/wiki#encoding-principle)).
After some tests, I found that it's the "Inspire theme" part that raises the error
```
Error in from_element_obj != item$attrs$element$value : 
  comparaison (2) possible seulement pour les types liste et atomique
``` 
The Inspire theme part:

```
> kwd1 <- ISOKeywords$new()
> anc1 <- ISOAnchor$new(name = "Environmental monitoring facilities", href = "http://inspire.ec.europa.eu/theme/ef")
> kwd1$addKeyword(anc1)
> kwd1$setKeywordType("theme")
> th <- ISOCitation$new()
> th_ref <- ISOAnchor$new(name = "GEMET - INSPIRE themes, version 1.0", href="http://www.eionet.europa.eu/gemet/inspire_themes")
> th$setTitle(th_ref)
> inspire_date <- ISODate$new()
> inspire_date$setDate(as.Date("2008-06-01"))
> inspire_date$setDateType("publication")
> th$addDate(inspire_date)
> kwd1$setThesaurusName(th)
> IDENT$addKeywords(kwd1)
```
The Inspire elements do not have to be converted in EML, but they should be skipped?

**Comment by eblondel** [comment]
Indeed, the should be skipped or taken as simple keyword, I'm going to have a look ASAP to this bug.

**Comment by eblondel** [comment]
@juliettefabre i've pushed some R code to fix the bug you reported. Can you try to restart, reinstall _geometa_ and see if ``as(md, "emld")`` works for you? Thanks

**Comment by juliettefabre** [comment]
Yes now it's OK even with Inspire themes.

However I noticed something wrong in keywords conversion:
- keywords with thesaurus are not converted
- keywords without thesaurus are assigned to the coverage > taxonomicCoverage section and don't appear in the keywordSet section:

```
> md
[...]
........|-- descriptiveKeywords <ISOKeywords>
............|-- keyword <ISOAnchor>
................|-- value: Environmental monitoring facilities
[...]
............|-- type <ISOKeywordType>: theme {keyword identifies a particular subject or topic}
................|-- value: theme
............|-- thesaurusName <ISOCitation>
................|-- title <ISOAnchor>
....................|-- value: GEMET - INSPIRE themes, version 1.0
................|-- date <ISODate>
....................|-- date: 2008-06-01
....................|-- dateType <ISODateType>: publication {date identifies when the resource was issued}
........................|-- value: publication
........|-- descriptiveKeywords <ISOKeywords>
............|-- keyword <ISOAnchor>
................|-- value: biogeochemistry
[...]
............|-- type <ISOKeywordType>: theme {keyword identifies a particular subject or topic}
................|-- value: theme
............|-- thesaurusName <ISOCitation>
................|-- title: GEMET
................|-- date <ISODate>
....................|-- date: 2010-01-13
....................|-- dateType <ISODateType>: publication {date identifies when the resource was issued}
........................|-- value: publication
........|-- descriptiveKeywords <ISOKeywords>
............|-- keyword: REC-THAU
............|-- keyword: Lagoons
............|-- type <ISOKeywordType>: theme {keyword identifies a particular subject or topic}
................|-- value: theme
[...]
```


```
> as(md, "emld")
access: []
additionalMetadata: []
citation: []
dataset:
  [...]
  coverage:
    taxonomicCoverage:
      taxonomicClassification:
      - taxonRankName: Genus
        taxonRankValue: REC-THAU
        taxonomicClassification:
          taxonRankName: Species
          taxonRankValue: .na.character
      - taxonRankName: Genus
        taxonRankValue: Lagoons
        taxonomicClassification:
          taxonRankName: Species
          taxonRankValue: .na.character
  keywordSet:
  - keywordThesaurus: GEMET - INSPIRE themes, version 1.0
    keyword: []
  - keywordThesaurus: GEMET
    keyword: []
 [...]
```

**Comment by eblondel** [comment]
@juliettefabre can you send me your R script preparing the ISO metadata to attempt the above conversion to EML/emld? thanks

**Comment by eblondel** [comment]
@juliettefabre i've fixed the first part of the issue where the Taxonomic coverage was wrongly filled with some keyword set (the one that didn't have a thesaurus name). I had a missing code to match this case.

I keep you update ASAP when the other weird mapping is fixed.

**Comment by eblondel** [comment]
@juliettefabre i've pushed additional fix for managing metadata lists mapping, and this fixed wrong behaviors with keywords handling. Could you please retry with the last metadata you tried? (and in case of issues again, send me the R code you use for your metadata)

**Comment by juliettefabre** [comment]
Hi,
Thanks, now the keywords without thesaurus are correctly converted, but those with a thesaurus (Inspire, GEMET, Agrovoc) don't appear in the keyword set.
```
> md
[...]
|-- descriptiveKeywords <ISOKeywords>
............|-- keyword <ISOAnchor>
................|-- value: hydrology
............|-- keyword <ISOAnchor>
................|-- value: atmosphere
............|-- type <ISOKeywordType>: theme {keyword identifies a particular subject or topic}
................|-- value: theme
............|-- thesaurusName <ISOCitation>
................|-- title: GEMET
................|-- date <ISODate>
....................|-- date: 2010-01-13 12:00:00
....................|-- dateType <ISODateType>: publication {date identifies when the resource was issued}
........................|-- value: publication
........|-- descriptiveKeywords <ISOKeywords>
............|-- keyword: GEK
............|-- keyword: SNO H+
............|-- type <ISOKeywordType>: theme {keyword identifies a particular subject or topic}
................|-- value: theme
```
```
> as(md, "emld")
keywordSet:
  - keywordThesaurus: GEMET - INSPIRE themes, version 1.0
    keyword: []
  - keywordThesaurus: GEMET
    keyword: []
  - keywordThesaurus: AGROVOC
    keyword: []
  - keyword:
    - GEK
    - SNO H+
```
Juliette

**Comment by eblondel** [comment]
@juliettefabre The issue was not related to thesaurus but list of anchors (here on keywords) that are not converted. I've applied a fix, now it is ok.

**Comment by juliettefabre** [comment]
OK thanks!
