### ISSUE TITLE
Inspire validation don't pass anymore with the complete example

### ISSUE THREAD

**Issue by juliettefabre** [eblondel/geometa#162]
Hi,

With the latest geometa@master, the [complete example provided in the wiki](https://github.com/eblondel/geometa/wiki#encoding-principle) is not Inspire compliant anymore. 

You can find the report [here](http://inspire.ec.europa.eu/validator/v2/TestRuns/50842953-e7b6-4b1f-93c1-e6d971318318.html) (problems in Identification and Data quality).

Maybe it's normal as the validator version changed, sorry I'm a little confused with this Inspire validation :)

**Comment by eblondel** [comment]
@juliettefabre I'm going to provide an updated example for INSPIRE and let you know

**Comment by eblondel** [comment]
I've updated the wiki, and added an R script [here](https://github.com/eblondel/geometa/blob/master/inst/extdata/examples/metadata.R). The output XML is available [here](https://github.com/eblondel/geometa/blob/master/inst/extdata/examples/metadata.xml). This example provides you a skeleton how to be 100% valid according to the [Common Requirements for ISO/TC 19139:2007 based INSPIRE metadata records](https://github.com/inspire-eu-validation/metadata/tree/2.0/common).

Let me know

**Comment by juliettefabre** [comment]
Thanks a lot, I updated my code based on your new example and now it passes Inspire validation :)
