### ISSUE TITLE
IANA mimetypes loading

### ISSUE THREAD

**Issue by maelle** [eblondel/geometa#188]
:wave: here too! :grin:

I was wondering why IANA mimetypes need to be loaded in every session vs cached somewhere? Do they change very often?

Cc @annakrystalli

**Comment by eblondel** [comment]
These are reference datasets required for the functioning of geometa, fetched from the web repository. I don't know if they change often, likely to change but that 's not really the point. I should not have to maintain any local copy so they are fetched from the source of truth. IANA registry load is not time-consuming. geometa is expected to be extended with other data registries like IANA, and when possible they will be fetched from the web source of truth.

**Comment by maelle** [comment]
Ok, makes sense, thank you!
