### ISSUE TITLE
Writing EML from ISO give EML not validated

### ISSUE THREAD

**Issue by yvanlebras** [eblondel/geometa#192]
I continue to test geometa to import ISO 19115 metadata documents, validate it, convert to EML, and validate the EML.

Here is my actual code:

```
install.packages("ncdf4")
require("devtools")
install_github("eblondel/geometa")
#remotes::install_github("eblondel/geometa")
library("geometa")
library("ncdf4")

# Test depuis catalogue Indores http://indores-tmp.in2p3.fr/geonetwork/srv/fre/catalog.search#/metadata/112ebeea-e79c-422c-8a43-a5a8323b446b
# <!--ISO 19139 XML compliance: NO-->
#xml <- xmlParse("~/1_PNDB/0_USe_cases/ISO2EML_indores/112ebeea-e79c-422c-8a43-a5a8323b446b.xml")

# test en mode URL
readISO19139(url="http://indores-tmp.in2p3.fr/geonetwork/srv/api/records/112ebeea-e79c-422c-8a43-a5a8323b446b/formatters/xml?approved=true")

# validate iso 
library("httr")
md$encode()

# write eml from iso
my_emld <- as(md, "emld")

# validate EML document
library(EML)
eml_validate(my_emld)
```

It appears EML are not valide with the ISO documents I tested. 

One reason is the "system" attribute who must be filled, maybe we can propose an option in the geometa command to add it as it seems to me we will always have such issue OR/AND propose to automaticaly fill this attribute with a hash or something else...

Another is the "pubDate" element who seems to not be put at the good place.

With this ISO document http://indores-tmp.in2p3.fr/geonetwork/srv/api/records/112ebeea-e79c-422c-8a43-a5a8323b446b/formatters/xml?approved=true, Ican't generate an EML and here is the stdout:
`Error in x[["geographicElement"]] : subscript out of bounds`

If you have any feedback on it, I continue my tests!

**Comment by eblondel** [comment]
we might have an issue in the mapping function, and have to debug this. Right now,  no idea what could be the issue.

**Comment by eblondel** [comment]
@yvanlebras checking carefully your ISO 19139 metadata sheet XML is malformed, they are quoted elements within the XML. You should fix it first.
