### ISSUE TITLE
Some dates ('publication', 'creation', 'lastRevision', ....) are not generated correctly in comparaison to GN output xml

### ISSUE THREAD

**Issue by kikislater** [eblondel/geometa#194]
Tested on publication date : 

When uploading metadata with GeoFlow we get the following error if we put for example `publication:2022-07-22` => 

![image](https://user-images.githubusercontent.com/13238064/180985807-a959e073-d0bd-4fc1-b13d-614a09d5878b.png)

So I found the error and it's present in generated xml : `gmd:CI_DateTypeCode` could be self closed.

To be clear let's see difference between not valid date and valid one:
Generated by geometa through GeoFlow (I put /gmd:title to locate block in xml):

```
          </gmd:title>
          <gmd:date>
            <gmd:CI_Date>
              <gmd:date>
                <gco:Date>2022-07-22</gco:Date>
              </gmd:date>
              <gmd:dateType>
                <gmd:CI_DateTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode" codeListValue="publication" codeSpace="ISOTC211/19115">publication</gmd:CI_DateTypeCode>
              </gmd:dateType>
            </gmd:CI_Date>
          </gmd:date>
```

Corrected and uploaded to GeoNetwork though Web interface return a successful publication date : 
```
          </gmd:title>
          <gmd:date>
            <gmd:CI_Date>
              <gmd:date>
                <gco:Date>2022-07-22</gco:Date>
              </gmd:date>
              <gmd:dateType>
                <gmd:CI_DateTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode" codeListValue="publication" codeSpace="ISOTC211/19115"/>
              </gmd:dateType>
            </gmd:CI_Date>
          </gmd:date>
```

![image](https://user-images.githubusercontent.com/13238064/180987117-32c59ade-2bf6-4d22-9c3c-3ca93a3386b9.png)

I tried to modify gmxCodelists.xml and ML_gmxCodelists.xml which contains this publication block but without success

Edit: Tested in GeoNetwork 3.12 and 4.2.0

Additionnal notes : If we create a new metadata from GN Web GUI and publication date if will generate the following xml without `</gmd:CI_DateTypeCode>`: 

`<gmd:CI_DateTypeCode codeListValue="publication" codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode"/>`

**Comment by eblondel** [comment]
From XML ISO validity, I get valid XML, if I do:

```R
test = ISODate$new()
test$setDate(Sys.Date())
test$setDateType("publication")
test$encode()
```

I don't see anything in the ISO schema that prevents from adding the text value associated with a codelist value. The ISO validity check done in `$encode()` is checked against the XML Schemas.
This said it's not the first time I see discrepancies between XML ISO Schemas validity done outside (in geometa) vs. what GN does. We should investigate why we get these discrepancies, whether GN proceeds with more checks (using a schematron) on content, that we don't do in geometa.

**Comment by kikislater** [comment]
Ok I will fill an issue on GN

**Comment by kikislater** [comment]
Bug is in GeoNetwork => https://github.com/INSPIRE-MIF/helpdesk-validator/issues/106

**Comment by eblondel** [comment]
Ok closing here, since it deals with Geonetwork
